DROP TABLE users
DROP TABLE recipes
DROP TABLE user_recipe
DROP TABLE family_recipes
DROP TABLE recipe_ingredients
DROP TABLE recipe_instructions
DROP TABLE family_recipe_ingredients
DROP TABLE cuisine
DROP TABLE recipes_cuisine
DROP TABLE diet
DROP TABLE recipes_diet
DROP TABLE intolerance
DROP TABLE recipes_intolerance